set(FFmpeg_ROOT "$ENV{FFMPEG_ROOT}")
set(FFmpeg_INCLUDE_DIR "${FFmpeg_ROOT}/include")
set(FFmpeg_FOUND TRUE)
mark_as_advanced(FFmpeg_INCLUDE_DIR)

if(FFmpeg_FOUND AND NOT TARGET FFmpeg::header-only)
  add_library(FFmpeg::header-only INTERFACE IMPORTED)
  set_property(TARGET FFmpeg::header-only PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${FFmpeg_INCLUDE_DIR}")
endif()

function(ImportFFmpeg name)
  if(FFmpeg_FOUND AND NOT TARGET FFmpeg::${name})
    add_library(FFmpeg::${name} STATIC IMPORTED)
    ## set_property(TARGET FFmpeg::${name} PROPERTY IMPORTED_LINK_INTERFACE_LANGUAGES "C")
    set_property(TARGET FFmpeg::${name} PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${FFmpeg_INCLUDE_DIR}")
    set_property(TARGET FFmpeg::${name} PROPERTY IMPORTED_LOCATION "${FFmpeg_ROOT}/lib/${name}.a")
  endif()
endfunction()

ImportFFmpeg(libavcodec)
ImportFFmpeg(libavdevice)
ImportFFmpeg(libavfilter)
ImportFFmpeg(libavformat)
ImportFFmpeg(libswresample)
ImportFFmpeg(libswscale)
ImportFFmpeg(libpostproc)
ImportFFmpeg(libavutil)
ImportFFmpeg(libx264)
